### ISSUE TITLE
Update CI Pipeline Files from Latest Pattern

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/ComputerManagementDsc#383]
Copy the latest patterns for the `build.yml`, `build.ps1` and `azure-pipelines.yml` from the PR:
https://github.com/dsccommunity/xExchange/pull/471

# build.yml

```
####################################################
#      DscResource.DocGenerator Configuration      #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    MarkdownCodeRegularExpression:
      - '\`(.+?)\`' # Match inline code-block
      - '\\(\\)' # Match escaped backslash
      - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
      - '_(.+?)_' # Match Italic (underscore)
      - '\*\*(.+?)\*\*' # Match bold
      - '\*(.+?)\*' # Match Italic (asterisk)
```

```
  publish:
    - publish_module_to_gallery
    - Publish_Release_To_GitHub
    - Publish_GitHub_Wiki_Content
    - Create_ChangeLog_GitHub_PR
```

- Also add updated issue templates and related files:
- .github\ISSUE_TEMPLATE
- .github\CONTRIBUTING.md
- .github\PULL_REQUEST_TEMPLATE.md
- .github\ISSUE_TEMPLATE\General.md
- .github\ISSUE_TEMPLATE\Problem_with_resource.yml
- .github\ISSUE_TEMPLATE\Resource_proposal.yml
- .github\ISSUE_TEMPLATE\config.yml

Add SECURITY.md as well.
